In [1]:
#Numpy Arrays in 2D -_-, thats it
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
a=[[11,12,13],[21,22,23],[31,32,33]]
A=np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [2]:
A.ndim # This is not the rank of the matrix, this is mereley the level of tupling

2

In [3]:
A.shape #Rows and Coloumns

(3, 3)

In [4]:
A.size

9

In [5]:
# This is what the array looks like:
#   |A[0][0] A[0][1] A[0][2]| 
# A=|A[1][0] A[1][1] A[1][2]| 
#   |A[2][0] A[2][1] A[2][2]| 

A[0][0]

11

In [6]:
A[0,0]

11

In [7]:
# A[0][0] = A[0,0]

In [9]:
#Slicing

B=A[0:2,0:2]
B

array([[11, 12],
       [21, 22]])

In [11]:
#We can add the damn things
x=np.array([[11,12],[21,22]])
y=np.array([[31,32],[41,42]])
z=x+y
z

array([[42, 44],
       [62, 64]])

In [12]:
x_2=2*x
x_2

array([[22, 24],
       [42, 44]])

In [13]:
z=x*y
z

array([[341, 384],
       [861, 924]])

In [14]:
z=np.dot(x,y)
z

array([[ 833,  856],
       [1553, 1596]])

In [ ]:
# For Matrix Multiplication A.B RowCount(A) must equals ColoumnCount(B)